apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hmg
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- name: docker-nexus.example.com/api-cassandra-hmg
  newName: docker-nexus.example.com/api-cassandra-hmg
  newTag: 9c3bce228e0ef3199c59a09c4afb5d4474f12a89
