apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventlistenersa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-apicassandra-eventlistener-binding
subjects:
  - kind: ServiceAccount
    name: eventlistenersa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-apicassandra-eventlistener-clusterbinding
subjects:
  - kind: ServiceAccount
    name: eventlistenersa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
