apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-cassandra-app-prod
spec:
  destination:
    name: ""
    namespace: "prod"
    server: "https://kubernetes.default.svc"
  source:
    path: api-cassandra-full/overlays/production
    repoURL: "https://github.com/venanciobernardes/gitops.git"
    targetRevision: HEAD
  sources: []
  project: apicassandra-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
