apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- name: docker-nexus.example.com/api-cassandra-prod
  newName: docker-nexus.example.com/api-cassandra-prod
  newTag: fd7f49eb1401d75758f82ce5be599cfffad3ec96
