apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
patchesStrategicMerge:
- deployment.yaml

resources:
- ../../base
images:
- name: docker-nexus.example.com/api-cassandra-dev
  newName: docker-nexus.example.com/api-cassandra-dev
  newTag: 4e86e90fba1dc5eb32b4722c201ed090a4095e64
