apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: apicassandra-prod-listener
spec:
  serviceAccountName: eventlistenersa
  triggers:
    - triggerRef: trigger-apicassandra-prod
  resources:
    kubernetesResource:
      serviceType: ClusterIP
      servicePort: 8080
